# Use the official Node.js 14
FROM node:14 as build

# Set the working directory inside the container
WORKDIR /app

# Copy the package.json and package-lock.json files to the working directory
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy the entire project directory to the working directory
COPY . .

# Expose port 3000
EXPOSE 3000

# Start Vite.js in development mode
CMD ["npm", "run", "dev"]
