# Production with static files
version: '3.1'
services:
  nginx:
    image: adomanski/mern-soccer:nginx-latest
    restart: always
    ports:
      - '80:80'
    depends_on:
      - server
      - mongo
    environment:
      - VITE_SERVER_URL=${VITE_SERVER_URL}
    networks:
      - app-network

  server:
    image: adomanski/mern-soccer:server-latest
    restart: always
    depends_on:
      - mongo
    ports:
      - '3001:3001'
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
