# Development with hot reload
# Remove all from git stage

version: '3.1'
services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data:/data/db

  server:
    container_name: backend
    restart: always
    depends_on:
      - mongo
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    env_file:
      - ./backend/.env

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
      - mongo
    environment:
      - NODE_ENV=development

  root:
    container_name: name
