# The name of the workflow.
name: Build and Deploy

# Run the workflow when code is pushed to the main branch
on:
  push:
    branches:
      - master

# Set environment variables
env:
  MONGO_URL: ${{ secrets.MONGO_URL }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  PORT: ${{ secrets.PORT }}
  VITE_SERVER_URL: ${{ secrets.VITE_SERVER_URL }}

# This is the workflow that is being run.
jobs:
  build-and-deploy:
    # This is telling GitHub to run the workflow on the latest version of Ubuntu.
    runs-on: ubuntu-latest
    steps:
      # Checkout the code from the GitHub repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install dependencies and run tests for the client application
      # - name: Install and Test Client
      #   working-directory: ./client
      #   run: |
      #     npm install

      # Install dependencies, export environment variables to be used by application and run tests for the server application
      # - name: Install Server
      #  working-directory: ./backend
      #  run: |
      #    npm install
      #    export MONGO_URL=$MONGO_URL
      #    export JWT_SECRET=$JWT_SECRET
      #    export PORT=$PORT

      # Build a Docker image for the client application
      # Here I don't need this because I serve the client with Nginx
      # - name: Build Client Docker Image
      #   working-directory: ./frontend
      #   # Build image with tag adomanski/mern-soccer:client
      #   run: |
      #     docker build -t adomanski/mern-soccer:client-${{github.run_number}} -t adomanski/mern-soccer:client-latest .

      # Build a Docker image for the server application
      - name: Build Server Docker Image
        working-directory:
          ./backend
          # Build image with tag adomanski/mern-soccer:server
        run: |
          docker build -t adomanski/mern-soccer:server-${{github.run_number}} -t adomanski/mern-soccer:server-latest .

      # Build a Docker image for the NGINX
      - name: Build NGINX Docker Image
        working-directory: ./frontend
        # Build image with tag adomanski/mern-soccer:nginx
        run: |
          docker build -t adomanski/mern-soccer:nginx-${{github.run_number}} -t adomanski/mern-soccer:nginx-latest .

      # Log in to Docker Hub using credentials from repository secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push the Docker images to Docker Hub
      - name: Push Docker Images to Docker Hub
        run: |
          docker push adomanski/mern-soccer:server-${{github.run_number}}
          docker push adomanski/mern-soccer:nginx-${{github.run_number}}
          docker push adomanski/mern-soccer:server-latest
          docker push adomanski/mern-soccer:nginx-latest

      # This is the step that is deploying the application to Elastic Beanstalk.
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.EB_APP_NAME }}
          environment_name: ${{ secrets.EB_ENV_NAME }}
          region: ${{ secrets.EB_REGION }}
          version_label: 'version-${{ github.run_number }}'
          deployment_package: docker-compose.prod.yaml
